//!  Transaction extension for AMQP management link

use fe2o3_amqp::transaction::TransactionExt;

/// Transaction extension for AMQP management link
pub trait ManagementLinkTransactionExt: TransactionExt {
    /// Future generated by `ManagementLinkTransactionExt::send_request`
    type RequestFut;

    /// Future generated by `ManagementLinkTransactionExt::call`
    type CallFut;

    // fn send_request(&mut self,)

}