[package]
name = "protocol_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
serde = "1"
serde_json = "1"
fe2o3-amqp = { path = "../../fe2o3-amqp", default-features = false, features = ["acceptor", "transaction", "scram", "tracing", "log"] }
fe2o3-amqp-ws = { path = "../../fe2o3-amqp-ws" }
fe2o3-amqp-ext = { path = "../../fe2o3-amqp-ext" }
tokio = { version = "1", features = ["net", "macros", "rt-multi-thread", "rt", "time"] }
tracing = "0.1.31"
tracing-subscriber = "0.3.9"
tokio-native-tls = "0.3.0"
native-tls = "0.2.8"
env_logger = "0.9.1"
